# This is a basic workflow to help you get started with Actions

name: Re-generate SBOMs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  make_sboms:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          lfs: false

      - name: test thing
        run: |
          date > lfsfiles/test.json

      - name: Commit new results
        run: |
          git pull --no-edit
          git config user.email "sbomer@myorg.com"
          git config user.name "SBOM Updater"
          git add ./lfsfiles/*
          git commit -s -a -m "update results"
          git push origin